### ISSUE TITLE
Load CSS only from child theme

### ISSUE THREAD

**Issue by pothi** [pothi/twentyseventeen-child-tinywp#1]
Don't use parent theme's CSS as it is.

We need to make changes in parent's CSS, especially with the following declaration...

`body { font-family: 'Some web font', sans-serif; }`

We use Font Face Observer where we need to change it to

```css
body { font-family: sans-serif; }
.our-unique-class body { font-family: 'Some web font', sans-serif; }
```
